# Generated by Django 2.2 on 2019-04-03 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_eventpost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpost',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventpost',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventpost',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
