# Generated by Django 2.2 on 2019-04-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_eventpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
