# Generated by Django 2.2 on 2019-04-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20190403_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpost',
            name='status',
            field=models.SlugField(default='published'),
        ),
    ]
